### ISSUE TITLE
Error forwarding the new session cannot find :

### ISSUE THREAD

**Issue by fengkingcheng** [paypal/docker-selion#10]
HI,
Fail to run test case with gird server,grid server and appium server both are in local,appium server register to grid server successfully.

appium version:1.5.2
xcode version :7.3
node version :6.1.0

my configuration for nodeconfig and testngxml as follow:
nodeconfig:
{
    "capabilities": [
    {
        "platformName": "IOS",
        "platformVersion": "9.3",
        "deviceName": "iphone 6"
        }
    ],
    "configuration": {
    "role": "node",
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubHost": "127.0.0.1",
    "hubPort": 4444
    }
} 
testngxml:
<parameter name="mobileNodeType" value="appium" />
    <parameter name="seleniumhost" value="127.0.0.1" />
    <parameter name="seleniumport" value="4444" />

```
<parameter name="appPath" value="/Users/jexing/Documents/PageObjects.app"/>
<parameter name="mobilePlatform" value="IOS"/>
<parameter name="mobileDevice" value="iphone:9.3"/>
<parameter name="mobileDeviceType" value="iPhone 6"/>
```

error log:
org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: Error forwarding the new session cannot find : Capabilities [{app=/Users/jexing/Documents/PageObjects.app, acceptSslCerts=true, platformVersion=9.3, name=com.paypal.selion.mobile.sample.TestTapPage:testSingleTap(), mobileNodeType=appium, language=en, javascriptEnabled=true, locale=en_US, platformName=iOS, version=, deviceName=iPhone 6, unexpectedAlertBehaviour=ignore}]
Command duration or timeout: 9 milliseconds

**Comment by mach6** [comment]
@fengkingcheng What does this have to do with the docker-selion component? 

Also, are you using a version of SeLion that is not merged to the `develop` branch -- such as this pull request? https://github.com/paypal/SeLion/pull/265  The reason I ask this is the parameters `mobileDevice`, `movileDeviceType` and `mobilePlatform` are not (yet) available in any official SeLion release or develop version. 

This said, your problem is going to be how Selenium matches the requested desired capabilities with those that were provided. For mobile nodes, there are special considerations / extra effort involved in making the request match the server's capabilities. If you use SeLion Enhanced Grid (-role hub) and attach the appium node to it, you will likely not have this issue. We have a `MobileCapabilityMatcher` which deals with this concern.

In the future, it may help to ask support-like questions on either our gitter.im channel or google group.

Thanks!

All things considered, I'm going to close this issue.
